apiVersion: v1
kind: Service
metadata:
  name: {{ include "boo-chart.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: {{ include "boo-chart.name" . }}
